// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBqgnxItp8tO2hl5JgBtgrWcZlK7C_HKPc',
    appId: '1:743765363743:web:7048ef7a22980d4cef192a',
    messagingSenderId: '743765363743',
    projectId: 'ijabqabul',
    authDomain: 'ijabqabul.firebaseapp.com',
    storageBucket: 'ijabqabul.firebasestorage.app',
    measurementId: 'G-VF03QHPD78',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbov0BruMmIF1KsUzbH37ooZ9B6O_upEs',
    appId: '1:743765363743:android:360a18b9da82cfa5ef192a',
    messagingSenderId: '743765363743',
    projectId: 'ijabqabul',
    storageBucket: 'ijabqabul.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBqgnxItp8tO2hl5JgBtgrWcZlK7C_HKPc',
    appId: '1:743765363743:web:f7fa1cf318e5a641ef192a',
    messagingSenderId: '743765363743',
    projectId: 'ijabqabul',
    authDomain: 'ijabqabul.firebaseapp.com',
    storageBucket: 'ijabqabul.firebasestorage.app',
    measurementId: 'G-9Q9VY1BCSL',
  );
}
