import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;
import 'package:printing/printing.dart';
import 'package:my_app/models/wedding_planner_package.dart';

class PackagePdfService {
  Future<void> generateAndShareComparison(
    List<WeddingPlannerPackage> packages,
  ) async {
    if (packages.isEmpty) return;

    final doc = pw.Document();
    final generatedOn = DateFormat('d MMMM yyyy').format(DateTime.now());

    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(32),
        build: (context) => [
          pw.Center(
            child: pw.Text(
              'IjabQabul',
              style: pw.TextStyle(
                fontSize: 24,
                fontWeight: pw.FontWeight.bold,
              ),
            ),
          ),
          pw.SizedBox(height: 8),
          pw.Center(
            child: pw.Text(
              'Vendor Comparison',
              style: pw.TextStyle(fontSize: 16),
            ),
          ),
          pw.Divider(),
          pw.SizedBox(height: 12),
          _buildComparisonTable(packages),
          pw.SizedBox(height: 24),
          pw.Text('Generated on: $generatedOn'),
          pw.Text('Generated by: IjabQabul Wedding Planner'),
        ],
      ),
    );

    await Printing.layoutPdf(onLayout: (_) async => doc.save());
  }

  pw.Widget _buildComparisonTable(List<WeddingPlannerPackage> packages) {
    final rows = <({String label, List<String> values})>[
      (
        label: 'Starting Price',
        values: packages.map((p) => p.formattedPrice).toList(),
      ),
      (
        label: 'Decoration',
        values: packages.map((p) => p.decorationLevel).toList(),
      ),
      (
        label: 'Catering',
        values: packages.map((p) => '${p.cateringPax} Pax').toList(),
      ),
      (
        label: 'Duration',
        values: packages.map((p) => p.duration).toList(),
      ),
      (
        label: 'Venue',
        values: packages.map((p) => p.venueType).toList(),
      ),
      (
        label: 'Makeup',
        values: packages.map((p) => p.makeupLevel).toList(),
      ),
      (
        label: 'Location',
        values: packages.map((p) => p.locationName).toList(),
      ),
      (
        label: 'Photography',
        values: packages.map((p) => p.photographyDetail).toList(),
      ),
    ];

    return pw.Table(
      border: pw.TableBorder.all(color: PdfColors.grey300),
      columnWidths: {
        0: const pw.FlexColumnWidth(1.2),
        for (var i = 0; i < packages.length; i++)
          i + 1: const pw.FlexColumnWidth(1.5),
      },
      children: [
        pw.TableRow(
          decoration: const pw.BoxDecoration(color: PdfColors.grey200),
          children: [
            _cell('Feature', bold: true),
            ...packages.map((p) => _cell(p.name, bold: true)),
          ],
        ),
        ...rows.map(
          (row) => pw.TableRow(
            children: [
              _cell(row.label, bold: true),
              ...row.values.map(_cell),
            ],
          ),
        ),
      ],
    );
  }

  pw.Widget _cell(String text, {bool bold = false}) {
    return pw.Padding(
      padding: const pw.EdgeInsets.all(8),
      child: pw.Text(
        text,
        style: pw.TextStyle(
          fontSize: 10,
          fontWeight: bold ? pw.FontWeight.bold : pw.FontWeight.normal,
        ),
      ),
    );
  }
}
